### ISSUE TITLE
`new-tr.py` 가 작동하지 않아요

### ISSUE THREAD

**Issue by wzrabbit** [kiwiyou/boj-user-translation#173]
안녕하세요!

며칠 전부터, `new-tr.py` 를 터미널에서 실행하면 문제에 대응되는 HTML 파일이 생성되는 대신, 아래의 오류가 발생하는 것을 확인했습니다.
![image](https://github.com/kiwiyou/boj-user-translation/assets/87642422/39df3bd2-85a4-4bd9-81ed-bde2e50a6c89)
```
Error: substring not found
```
해당 문제의 HTML 문서가 깨져서 다른 문제 번호로도 시도해 보았지만, 결과는 같더라고요.

그래서 `new-tr.py` 를 직접 디버깅해서 어떤 HTML 파일을 불러오는지를 확인해 보았는데요, 아래와 같이 `403 Forbidden`으로 막힌 HTML 을 불러오더라고요. 크롤링 과정에서 문제가 있을 것이 예상됩니다. 크롤링으로 가져온 HTML 문서가 `403 Forbidden` fallback 페이지여서, 이후 가져온 데이터를 파싱하는 과정에서 문제가 생겨 `Error: substring not found` 오류가 발생한 것 같습니다.
![image](https://github.com/kiwiyou/boj-user-translation/assets/87642422/6e225742-36ca-4f65-9a78-8fb0064488b5)
```html
<html>
  <head>
    <title>403 Forbidden</title>
  </head>
  <body>
    <center>
      <h1>403 Forbidden</h1>
    </center>
  </body>
</html>
```
백준에서 특정 크롤링을 방어하는 로직을 사용한다는 이야기를 듣기는 했지만, 사실인지는 잘 모르겠어요.
구동 환경은 `Windows 10`, `Python 3.12` 버전입니다.

쉬워 보이는 문제 같지는 않지만, 만약 해결이 가능하시다면 검토해 주시면 감사하겠습니다!

**Comment by kiwiyou** [comment]
User-Agent를 수정했습니다.
