### ISSUE TITLE
username은 Github id인가요? 백준 id인가요?

### ISSUE THREAD

**Issue by junah201** [kiwiyou/boj-user-translation#183]
[new-tr](https://github.com/kiwiyou/boj-user-translation/blob/main/new-tr.py)에서 사용되는 username은 Github id인가요? 백준 id인가요?

**Comment by kiwiyou** [comment]
@junah201 번역 버튼에 표시되기를 원하시는 아무 이름을 입력하시면 됩니다.

**Comment by junah201** [comment]
넵 감사합니다 👍
