### ISSUE TITLE
new_tr.py가 macOS 환경에서 제대로 작동하지 않습니다.

### ISSUE THREAD

**Issue by ldhhello** [kiwiyou/boj-user-translation#62]
```
Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
from http.client import HTTPSConnection
```

제 macOS 환경에서 new_tr.py가 위의 오류를 띄우며 제대로 작동하지 않습니다. (macOS Ventura 13.4.1, Apple M1 Pro 환경에서 테스트했습니다)

macOS에서도 new_tr.py가 제대로 작동하게 수정해 주세요.

**Comment by kiwiyou** [comment]
https://github.com/kiwiyou/boj-user-translation/commit/ca1dcf7a296834ec5260c33e25af3b92b3f12452 에서 수정했습니다.
