### ISSUE TITLE
불가리아어 및 일본어 오타 수정 필요

### ISSUE THREAD

**Issue by jh05013** [kiwiyou/boj-user-translation#70]
다음 두 문제는 조건이 부족하여 `typo` 명의로 추가해야 하는데, 그러려면 새 언어가 지원되어야 합니다.

- 불가리아어: [24297 НАЙ-МНОГО ЕДНАКВИ](https://www.acmicpc.net/board/view/93475)
- 일본어: [5621 問題 5](https://www.acmicpc.net/board/view/82491)

**Comment by kiwiyou** [comment]
해당하는 문제들은 언어가 하나만 존재하여 `Original`을 사용하시면 됩니다. README를 수정했습니다. (37b37a26e25d008ca94871aa72d324cfd3c9d0df)
